---
openapi: 3.0.2
info:
  title: order-api
  version: 1.0.1
  description: |-
    Used to get order information.
    AHHHHHHHHHHHHHHHH
paths:
  /orders:
    summary: Gets a list of active orders. Want to cause CONFLIUCT!
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
          description: Successfully received list of active orders.
      summary: Gets a list of all active orders in the system.
  /orders/ids/{orderId}:
    summary: Used to interact with a specific order.
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: Successfully retrieved the specified order.
      summary: Gets the order specified.
    parameters:
    - name: orderId
      description: The id of the order to retrieve.
      schema:
        type: string
      in: path
      required: true
  /orders/states/{state}:
    summary: Used to interact with orders with a given state.
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
          description: Successfully retrieved orders with the given state.
      summary: Gets a list of orders in the given state.
    parameters:
    - name: state
      description: Orders retrieved will be in this given state.
      schema:
        type: string
      in: path
      required: true
  /orders/{orderId}/cases:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Case'
          description: Successfully retrieved cases for the given order.
      summary: Gets a list of cases of the associated order.
    parameters:
    - name: orderId
      description: The order id related to the cases.
      schema:
        type: string
      in: path
      required: true
components:
  schemas:
    Order:
      title: Root Type for order
      description: An order in the system.
      required:
      - CreateDate
      type: object
      properties:
        CreateDate:
          description: The creation date of the order.
          type: string
        Id:
          type: string
        Status:
          type: string
        Cases:
          description: Array of cases in the order.
          type: array
          items:
            $ref: '#/components/schemas/Case'
      example:
        id: blah
        status: active
    Case:
      title: Root Type for case
      description: A case in the system.
      type: object
      properties:
        id:
          type: string
        sku:
          type: string
      example:
        id: blah
        sku: blah
